# See https://pre-commit.com for more information
default_language_version:
  # default language version for each language used in the repository
  python: python3.10

repos:
  - repo: local
    hooks:
      - id: generate-requirements
        name: generate-requirements
        entry: python3.10 -m poetry export -f requirements.txt --output requirements.txt
        language: system
        types: [file]
        pass_filenames: false
        stages: [commit]
        files: 'pyproject\.toml|poetry\.lock'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
        exclude: (charts/.*|.gitlab-ci.yml)
      - id: detect-private-key
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-print",
            "flake8-simplify",
        ]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.7.0'
    hooks:
      - id: autopep8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        language_version: python3.10
        args:
          - --no-warn-unused-ignores
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ['-iii', '-ll']
